### ISSUE TITLE
创造模式物品栏又出现了奇怪的东西

### ISSUE THREAD

**Issue by touhouzun** [0999312/SlashBlade-Japanese-Addon-Pack#3]
![2019-02-01_09 27 37](https://user-images.githubusercontent.com/31458903/52096949-c0a05080-2603-11e9-81d3-2adf2a124d9c.png)
![2019-02-01_09 27 50](https://user-images.githubusercontent.com/31458903/52096952-c26a1400-2603-11e9-9192-961e0c4014f8.png)
SJAP_V1.0.8_MC1.12.2，感觉和以前last smith是同类型问题。。。_(:з)∠)_

**Comment by 0999312** [comment]
??????

**Comment by touhouzun** [comment]
> ??????

#https://github.com/0999312/The-Last-Smith/issues/1
