### ISSUE TITLE
使用该附属拔刀攻击Alex的洞穴生物会产生崩溃

### ISSUE THREAD

**Issue by TheFlareStar-Re** [0999312/SlashBlade-Japanese-Addon-Pack#9]
版本是 1.20.1 1.1.6
日志如下
[crash-2024-10-13_11.55.39-server.txt](https://github.com/user-attachments/files/17353001/crash-2024-10-13_11.55.39-server.txt)

**Comment by 0999312** [comment]
已经紧急修复更新，请更新至1.1.7
